### ISSUE TITLE
AttributeError: 'str' object has no attribute 'removeprefix'

### ISSUE THREAD

**Issue by pieterhouwen** [alufers/mitmproxy2swagger#11]
```
printf "Hello World!\n"
```

I'm using mitmproxy2swagger on my Ubuntu 20.04 WSL instance and I'm running into a python error when running mitmproxy2swagger when using a HAR file.

Complete command and output:

```
pieter@supersecretstation:/downloads$ mitmproxy2swagger -i somefile.har -o outputfile -p https://sub.domain.tld
No existing swagger file found. Creating new one.
[                              ] 0.0%Traceback (most recent call last):
  File "/mnt/c/Users/Pieter/.local/bin/mitmproxy2swagger", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/Pieter/.local/lib/python3.8/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 116, in main
    path = strip_query_string(url).removeprefix(args.api_prefix)
AttributeError: 'str' object has no attribute 'removeprefix'
```

Maybe I'm running the wrong version of python?

Thanks!

```
exit 0
```

**Comment by pieterhouwen** [comment]
For those who are wondering:

Seems like 20.04 has a python lib which only goes to 3.8 while above mentioned "removeprefix" attribute is something introduced in python3.9 which is best supported on a later version of ubuntu.

After the OS upgrade the program worked fine
