### ISSUE TITLE
Broken Imports

### ISSUE THREAD

**Issue by TheBagarius** [alufers/mitmproxy2swagger#160]
I don't understand what is going on in the error message below.
Also I cannot call `mitmproxy2swagger` from the command line after installing it with `pip3 install mitmproxy2swagger`

bumping #153 

```
mitmproxy2swagger.py -i ~/Downloads/TMS-login\ flows -o ~/Download/tms_trials
Traceback (most recent call last):
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 16, in <module>
    from mitmproxy2swagger import console_util, swagger_util
  File "/Users/USER/Library/Python/3.9/lib/python/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 16, in <module>
    from mitmproxy2swagger import console_util, swagger_util
ImportError: cannot import name 'console_util' from partially initialized module 'mitmproxy2swagger' (most likely due to a circular import) (/Users/USER/Library/Python/3.9/lib/python/site-packages/mitmproxy2swagger/mitmproxy2swagger.py)
```

**Comment by josephwandery** [comment]
Hello,try installing it in a virtual environment.

**Comment by rithvikvibhu** [comment]
Looks like it's because the directory (mitmproxy2swagger) and the main file (`mitmproxy2swagger.py`) are of the same name. To confirm, renaming it to `mitmproxy2swagger_main.py` will make the script work.

But yeah, if installed globally properly, this should not be requried and works fine.
