### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Chlo-ob** [alufers/mitmproxy2swagger#172]
I'm installing on an updated, upgraded VMware instance of kali Linux. Busy with the apisec api penetration testing course. 

Used pip3 to install into the/opt/ directory. 
If I use the command to run the flow through mitmproxy2swagger it keeps saying: command not found.

**Comment by NelsonOmoniyi** [comment]
I am experiencing the same issue as well, have you been able to get a work-around outside github?

**Comment by Chlo-ob** [comment]
No I haven't managed to get this to work.  I have tried to use a docker container, python venv environment and still no luck.  I even reloaded a new kali vm instance, same error...  as well as on parrot os...  I really don't know what more to try.. or if I'm doing something wrong.  I initially kept getting python asigref errors,  but in the parrot os when I created a python virtual environment it installed perfectly but as soon as I input the command to run the flow through mitmproxy2swagger it keeps saying mitmproxy2swagger command not found...

**Comment by khargosh99** [comment]
I am also facing the same error. Trying to solve it from last 3 days

**Comment by Chlo-ob** [comment]
I also haven't managed to make it work.  The best bet would be to learn how to use the docker container method.  I managed to get it set up in a container, but I don't know much about Docker,  so another thing to learn and master....  Iv only just started to learn and use Linux so I guess its all about the learning curve..

**Comment by josephotrust** [comment]
Hi, I had the same issue. I received this warning:

WARNING: The script mitmproxy2swagger is installed in '/home/joeo/.local/bin' which is not on PATH.                                                     
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.   

I moved the install to /usr/local/bin and the command is now found.

sudo mv /home/joeo/.local/bin/mitmproxy2swagger /usr/local/bin

**Comment by vikas9452** [comment]
Getting same error but them i tried to install it using docker here is my process 
$ git clone git@github.com:alufers/mitmproxy2swagger.git
$ cd mitmproxy2swagger
$ docker build -t mitmproxy2swagger .
$ sudo docker run --rm mitmproxy2swagger -h

This worked well UNTIL i got the error 

$ sudo docker run --rm mitmproxy2swagger -i ../flows -o spec.yml -p http://[URL] -f flow
No existing swagger file found. Creating new one.
Traceback (most recent call last):
  File "/venv/bin/mitmproxy2swagger", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.10/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 179, in main
    for req in capture_reader.captured_requests():
  File "/venv/lib/python3.10/site-packages/mitmproxy2swagger/mitmproxy_capture_reader.py", line 112, in captured_requests
    with open(self.file_path, "rb") as logfile:
FileNotFoundError: [Errno 2] No such file or directory: '../flows'

File is there but still showing this error

**Comment by realp05h** [comment]
Was facing the same problem.

Create a python venv then pip install it in there:
python3 -m venv mitmproxy_venv

Then activate the venv:
source mitmproxy_venv/bin/activate

Now run:
pip3 install mitmproxy2swagger

As long as you're in that venv you can run the normal commands.

To jump out of the venv just run 'deactivate'.

**Comment by AndrewWalsh** [comment]
I have built an equivalent of this tool in case anyone needs another approach https://github.com/AndrewWalsh/demystify
