### ISSUE TITLE
Second time run of the tool gives an error

### ISSUE THREAD

**Issue by viraj2252** [alufers/mitmproxy2swagger#23]
Traceback (most recent call last):
  File "/opt/homebrew/bin/mitmproxy2swagger", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 125, in main
    path_template_regexes = [re.compile(path_to_regex(path))
  File "/opt/homebrew/lib/python3.10/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 125, in <listcomp>
    path_template_regexes = [re.compile(path_to_regex(path))
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/sre_parse.py", line 843, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 35

![image](https://user-images.githubusercontent.com/15133721/217254306-eba9ee9b-3a90-459d-ab95-c8c2f60eec04.png)

**Comment by alufers** [comment]
Fixed in 0.8.1
