### ISSUE TITLE
'str' object does not support item assignment in mitmproxy2swagger.py

### ISSUE THREAD

**Issue by krishna760** [alufers/mitmproxy2swagger#25]
└─$ pip install --no-cache-dir mitmproxy2swagger
Successfully installed mitmproxy2swagger-0.8.0
└─$ mitmproxy2swagger -i Downloads/flows -o spec.yml -p http://google.com
Traceback (most recent call last):
  File "/home/krish500/.local/bin/mitmproxy2swagger", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/krish500/.local/lib/python3.11/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 98, in main
    swagger['servers'] = []
    ~~~~~~~^^^^^^^^^^^
TypeError: 'str' object does not support item assignment
└─$ uname -a
Linux DESKTOP-18BPFD5 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux
$ mitmweb --version
Mitmproxy: 9.0.1
Python:    3.11.1
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
─$ python3 --version
Python 3.11.1

**Comment by jrgdiaz** [comment]
I'm receiving this same error.
