### ISSUE TITLE
RuntimeError: Cannot change server.via on open connection.

### ISSUE THREAD

**Issue by lttlrck** [alufers/mitmproxy2swagger#3]
Hey, this looks really useful. Gave it a go but got this error.

```
mitmproxy2swagger -i ~/Downloads/flows  -o test-api -p test-api
No existing swagger file found. Creating new one.
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy2swagger", line 8, in <module>
    sys.exit(main())
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 111, in main
    for f in freader.stream():
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/io/io.py", line 48, in stream
    yield FLOW_TYPES[mdata["type"]].from_state(mdata)
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/flow.py", line 165, in from_state
    f.set_state(state)
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/flow.py", line 160, in set_state
    super().set_state(state)
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/stateobject.py", line 47, in set_state
    setattr(self, attr, make_object(cls, val))
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/stateobject.py", line 94, in make_object
    return _process(typeinfo, val, True)
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/stateobject.py", line 56, in _process
    return typeinfo.from_state(val)
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/connection.py", line 331, in from_state
    server.set_state(state)
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/connection.py", line 353, in set_state
    self.via = state["via2"]
  File "/home/stuart/.local/lib/python3.10/site-packages/mitmproxy/connection.py", line 299, in __setattr__
    raise RuntimeError(f"Cannot change server.{name} on open connection.")
RuntimeError: Cannot change server.via on open connection.
```

[flows.zip](https://github.com/alufers/mitmproxy2swagger/files/8689785/flows.zip)

`mitmweb --mode upstream:http://172.18.0.2`

**Comment by alufers** [comment]
Hmmm it looks like your flow file somehow is corrupt, even mitmproxy itself cannot open it back.

I will investigate this further.

**Comment by lttlrck** [comment]
> Hmmm it looks like your flow file somehow is corrupt, even mitmproxy itself cannot open it back.
> 
> I will investigate this further.

Ok. Just checked and the version I used to save it doesn't reload it either... I'd put this on hold until I've had a chance to figure that out. Sorry.

**Comment by lttlrck** [comment]
mitmproxy actually prints the same error on load... 

It's caused by using upstream mode, if I use it as a plain proxy it's fine. 

Related: https://github.com/mitmproxy/mitmproxy/issues/5241

Thanks.
