### ISSUE TITLE
Cannot convert - TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by jugaltheshah** [alufers/mitmproxy2swagger#47]
Per the title, when I try to convert a flow to Swagger using `mitmproxy2swagger -i flows -o schema.yml -p api`, I get the following error:

```
No existing swagger file found. Creating new one.
Traceback (most recent call last):
  File "/opt/homebrew/bin/mitmproxy2swagger", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 168, in main
    for req in capture_reader.captured_requests():
  File "/opt/homebrew/lib/python3.11/site-packages/mitmproxy2swagger/har_capture_reader.py", line 114, in captured_requests
    for entry in data["log"]["entries"].persistent():
                 ~~~~^^^^^^^
TypeError: 'int' object is not subscriptable
```

Installed via `pip3 install mitmproxy2swagger`

**Comment by avicoder** [comment]
why did you close this issue , if it still not resolved!!

**Comment by CyberYeagerist** [comment]
not in my case
![image](https://github.com/alufers/mitmproxy2swagger/assets/91853873/5f7c1ae2-f309-4632-b80a-982327774caa)
