### ISSUE TITLE
No existing swagger file found. Creating new one.

### ISSUE THREAD

**Issue by morehwachege** [alufers/mitmproxy2swagger#85]
### Full error log.
``` No existing swagger file found. Creating new one.
Traceback (most recent call last):
  File "/home/[username]/.local/bin/mitmproxy2swagger", line 8, in <module>
    sys.exit(main())
  File "/home/[username]/.local/lib/python3.10/site-packages/mitmproxy2swagger/mitmproxy2swagger.py", line 178, in main
    for req in capture_reader.captured_requests():
  File "/home/[username]/.local/lib/python3.10/site-packages/mitmproxy2swagger/har_capture_reader.py", line 117, in captured_requests
    for entry in data["log"]["entries"].persistent():
TypeError: 'int' object is not subscriptable  
```

### Reproduce
```mitmproxy2swagger -i flows -o spec.yml -p https://goo.gle/api/v1```

**Comment by morehwachege** [comment]
Perfect response time...updating the Readme would help future users

**Comment by avicoder** [comment]
although it worked , the results are not listing ant routes.
```
openapi: 3.0.0
info:
  title: flowsun Mitmproxy2Swagger
  version: 1.0.0
servers:
- url: https://some.com/api
  description: The default server
paths: {}
x-path-templates:
# Remove the ignore: prefix to generate an endpoint with its URL
# Lines that are closer to the top take precedence, the matching is greedy
  []

```

**Comment by morehwachege** [comment]
Try without using any api prefix. Like this

![image](https://github.com/alufers/mitmproxy2swagger/assets/76877744/7a86488c-b184-4d31-9f53-5766a54feeb1)

**Comment by CyberYeagerist** [comment]
not in my case
![image](https://github.com/alufers/mitmproxy2swagger/assets/91853873/d9c18fb8-71dc-480e-a936-eb7dc9389019)
